name: tsuruo_kit
description: A toolkit created by `@htsuruo` that includes useful widgets, extensions, providers, and more.
version: 0.3.0
repository: https://github.com/htsuruo/flutter_tsuruo_kit

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.35.0
  riverpod_generator: ^3.0.3
