name: tsuruo_kit
description: A toolkit created by `@htsuruo` that includes useful widgets, extensions, providers, and more.
version: 0.2.2
repository: https://github.com/htsuruo/flutter_tsuruo_kit

environment:
  sdk: ^3.2.0

dependencies:
  # due to `flutter_test` depends on collection 1.17.2
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.35.0
